name: data-pipeline-workflow

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "35 0 * * *"

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: Checkout repo content
      # pulling all code from github repo
        uses: actions/checkout@v4
        with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # step 2
      - name: Setup Python
        uses: actions/setup-Python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      
      # step 3
      - name: Install dependencies
        run: pip install -r requirements.txt

      # step 4
      - name: Run data-pipeline
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: python data_pipeline.py

      # step 5
      - name: Check for changes
        id: git-check
        run: |  
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add.
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV

      # step 6
      - name: Commit and push if changes
        if: env.changes == 'true'
        run: |
          git commit -m "upload video index"
          git push


      
